version: '1.25'

networks:
  app-net:

volumes:
  database:
    source: /home/yait-iaz/data/database

  source_file:
    source: /home/yait-iaz/data/wordpress

services:
  nginx:
    build: ./nginx/Dockerfile
    networks: app-net
    port:
      -"443:443"
    expose:
      -"9000"
    volumes:
      -source_file:
        type: bind
        target: /var/www/wordpress

  mariadb:
    build: ./mariadb/Dockerfile
    networks: app-net
    expose:
      -"3306"
    env_file:
      - .env
    volumes:
      -database:
        type: bind
        target: /home/yait-iaz/data/database

  wordpress:
    build: ./wordpress/Dockerfile
    networks: app-net
    expose:
      -"3306"
      -"9000"
    volumes:
      -database:
        type: bind
        target: /var/www/database
      -source_file:
        type: bind
        target: /var/www/wordpress
    depends_on:
      - nginx
      - mariadb
    env_file:
      - .env